name: proyectomanu
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Se recomienda especificar un rango

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  url_launcher: ^6.3.2
  smooth_page_indicator: ^1.1.0
  chiclet: ^1.2.0
  camera: ^0.11.2
  shared_preferences: ^2.5.3
  image: ^4.5.4
  auto_size_text: ^3.0.0
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  awesome_notifications: ^0.10.1
  timezone: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # PAQUETES DE DESARROLLO (SOLO HERRAMIENTAS)
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding/
    - assets/images/animations/
    - assets/images/categorias/
    - assets/images/sprites/
    - assets/images/glosario/
    - assets/images/general/
    - assets/images/correo/
    - assets/icons/brands/
    - assets/images/logros/
    - assets/images/avatares/
  fonts:
    - family: Bunny
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.otf
    - family: Monse
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/applogo.png"

flutter_native_splash:
  color: "#77baff" # color claro
  color_dark: "#0d4cd8" # elige aquÃ­ tu color para modo oscuro
  image: assets/images/iconosplash.png

  android_12:
    image: assets/images/iconosplash.png
    color: "#77baff"
    color_dark: "#0d4cd8"

  web: false
